# Generated by Django 6.0.3 on 2026-03-11 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerObjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Career Objective', max_length=200)),
                ('content', models.TextField(default='', help_text='Your career goals and objectives')),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Career Objective',
                'verbose_name_plural': 'Career Objective',
            },
        ),
        migrations.CreateModel(
            name='HeroTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(help_text='Font Awesome icon class', max_length=50)),
                ('value', models.PositiveIntegerField(default=0)),
                ('label', models.CharField(max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='github_username',
            field=models.CharField(blank=True, default='', help_text='GitHub username for API integration', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='meta_description',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AddField(
            model_name='profile',
            name='meta_title',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, default='', help_text='Phone number with country code', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='short_intro',
            field=models.CharField(default='I build beautiful web applications', help_text='Short introduction for hero section', max_length=300),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='github',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='linkedin',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(default='Your Name', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='resume',
            field=models.FileField(blank=True, help_text='Upload PDF resume', null=True, upload_to='resume/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='title',
            field=models.CharField(default='Full Stack Developer', max_length=200),
        ),
    ]
