# Generated by Django 6.0.3 on 2026-03-29 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_profile_profile_image_alter_profile_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='resume_url',
            field=models.URLField(blank=True, default='', help_text='Direct URL to resume (e.g., Google Drive, Dropbox, or Cloudinary public URL)', max_length=500),
        ),
    ]
