# Generated by Django 6.0.3 on 2026-03-11 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Certification Name', max_length=200)),
                ('organization', models.CharField(default='Organization', max_length=200)),
                ('issued_date', models.DateField()),
                ('credential_id', models.CharField(blank=True, default='', help_text='Credential ID or URL', max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='certifications/')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Certification',
                'verbose_name_plural': 'Certifications',
                'ordering': ['-issued_date', 'order'],
            },
        ),
        migrations.CreateModel(
            name='CurrentlyLearning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Technology', max_length=100)),
                ('icon', models.CharField(default='fa-code', max_length=50)),
                ('progress', models.IntegerField(default=0, help_text='Learning progress 0-100')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Category', max_length=50)),
                ('icon', models.CharField(default='fa-code', help_text='Font Awesome icon', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Skill Category',
                'verbose_name_plural': 'Skill Categories',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('web', 'Web Development'), ('ai', 'AI / ML'), ('data', 'Data Analytics'), ('other', 'Other')], default='web', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='short_description',
            field=models.CharField(default='', help_text='Short description for cards', max_length=300),
        ),
        migrations.AlterField(
            model_name='education',
            name='degree',
            field=models.CharField(default='Degree', max_length=200),
        ),
        migrations.AlterField(
            model_name='education',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='education',
            name='field_of_study',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='education',
            name='institution',
            field=models.CharField(default='Institution', max_length=200),
        ),
        migrations.AlterField(
            model_name='experience',
            name='company',
            field=models.CharField(default='Company', max_length=200),
        ),
        migrations.AlterField(
            model_name='experience',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='experience',
            name='position',
            field=models.CharField(default='Position', max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='github_link',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='live_demo',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='tech_stack',
            field=models.CharField(default='', help_text='Comma-separated technologies', max_length=500),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(default='Project Title', max_length=200),
        ),
        migrations.AlterField(
            model_name='skill',
            name='icon',
            field=models.CharField(default='fa-code', help_text='Font Awesome class or emoji', max_length=50),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(default='Skill', max_length=100),
        ),
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='portfolio.skillcategory'),
        ),
    ]
