# Generated by Django 6.0.3 on 2026-03-27 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_certification_currentlylearning_skillcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='usage_description',
            field=models.CharField(blank=True, default='', help_text='Short description for tooltip on hover', max_length=200),
        ),
    ]
