# Generated by Django 6.0.3 on 2026-03-27 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_project_options_project_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='outcome',
            field=models.TextField(blank=True, default='', help_text='Results and insights from the project'),
        ),
        migrations.AddField(
            model_name='project',
            name='problem_statement',
            field=models.TextField(blank=True, default='', help_text='Problem addressed by this project'),
        ),
        migrations.AddField(
            model_name='project',
            name='solution',
            field=models.TextField(blank=True, default='', help_text='How the problem was solved'),
        ),
    ]
