# Generated by Django 6.0.3 on 2026-04-19 18:00

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_alter_certification_image_alter_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='document',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Certificate PDF document', max_length=255, null=True, verbose_name='document'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Certificate image (jpg, png, etc.)', max_length=255, null=True, verbose_name='image'),
        ),
    ]
